spring.application.name=ProducerApp
server.port=8080


#  common starting path for all apis
server.servlet.context-path=/api/v1/producer

# kafka brokers
spring.kafka.bootstrap-servers=localhost:29093,localhost:29094,localhost:29092

#  metadata refresh interval time
spring.kafka.producer.properties.metadata.max.age.ms=300000

# asking broker to reply only when all isr successfully get the events (basically follower gets data from leader)
spring.kafka.producer.acks=all

# Key and value serializer for producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer




# Record accumulator


# max time producer waits before sending events to broker
spring.kafka.producer.properties.linger.ms=20 

#  max batch size,send when batches reach(32KB), even if linger(20ms) has not expired
spring.kafka.producer.batch-size=32768

# total buffer memory for all batches:32MB (if full ,send() will get blocked till space created or max block time)
spring.kafka.producer.properties.buffer.memory=33554432 


# Max time send() blocks if buffer is full (default 60s), after this time, send() call will fail immediately 
spring.kafka.producer.properties.max.block.ms=60000 




#  compression
# compresses entire batch before sending
spring.kafka.producer.compression-type=snappy

#  sender thread
#  max retries on transient failures(network timeout, leader change etc).
spring.kafka.producer.retries=3


# max in flight requests
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

# # transactional
# spring.kafka.producer.transaction-id-prefix=producer-server-{server.port}


# spring.kafka.producer.properties.transaction.timeout.ms=60000